[workspace]
members = ["ents", "ents-admin", "ents-admin-api", "ents-sqlite", "ents-heed", "ents-test-suite"]
resolver = "2"

[workspace.package]
version = "0.3.3"
homepage = "https://github.com/blmarket/ents"
repository = "https://github.com/blmarket/ents"
edition = "2021"
authors = [ "blmarket@gmail.com" ]

[workspace.dependencies]
ents = { version = "0.3.2", path = "ents" }
ents-admin = { version = "0.3.2", path = "ents-admin" }
ents-sqlite = { version = "0.3.2", path = "ents-sqlite" }
ents-heed = { version = "0.3.2", path = "ents-heed" }
ents-test-suite = { version = "0.3.2", path = "ents-test-suite" }
ents-admin-api = { version = "0.3.2", path = "ents-admin-api" }
