[workspace]
members = ["ents", "ents-admin", "ents-admin-api", "ents-sqlite", "ents-heed", "ents-test-suite"]
resolver = "2"

[workspace.dependencies]
ents = { path = "ents" }
ents-admin = { path = "ents-admin" }
ents-sqlite = { path = "ents-sqlite" }
ents-heed = { path = "ents-heed" }
ents-test-suite = { path = "ents-test-suite" }
ents-admin-api = { path = "ents-admin-api" }
