[package]
name = "ents-admin"
version = "0.4.1"
authors = ["blmarket@gmail.com"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Admin APIs for ents"
repository = "https://github.com/blmarket/ents"
keywords = ["ent", "entity-framework", "admin"]

[dependencies]
ents.workspace = true
thiserror = "2"
